Creating a new image based on Airflow image, official one version 2.3.2
pubnative/docker-images pull request #157
Opened 2022-07-07 10:56 UTC by alifouzizadeh

I confirm that I have added:

- [ x] A comment to every Dockerfile with information about target repository and tag (version).
- [ x] Filled in readme on dockerhub and in this repo about how to build the image if some extra steps should be done.

2022-07-07 11:08 UTC, Konstantinos-Chaitas-PubNative requested changes
Why do you duplicate all files? You can just make the version configurable

2022-07-07 11:25 UTC, Konstantinos-Chaitas-PubNative commented
@alifouzizadeh this PR will get merged once we make sure it works. We are not keeping different manifests for different images, just the latest one. You can remove the old files and tag the new image with airflow-2 or something like this. Remember that we will still have the old(Airflow 1) images on Dockerhub

2022-09-28 12:28 UTC, mpasa approved these changes

2022-09-28 12:32 UTC, Konstantinos-Chaitas-PubNative approved these changes

2022-09-28 12:32 UTC, merged