Dso 606 ml flow deploy helm to cluster
pubnative/docker-images pull request #184
Opened 2023-05-22 08:08 UTC by pmittal-verve

I confirm that I have added:

- [ ] A comment to every Dockerfile with information about target repository and tag (version).
- [ ] Filled in readme on dockerhub and in this repo about how to build the image if some extra steps should be done.

2023-06-02 08:42 UTC, pmittal-verve commented
@Konstantinos-Chaitas-PubNative @annoyingllama Please review.

2023-06-06 13:41 UTC, Konstantinos-Chaitas-PubNative requested changes

2023-06-06 13:41 UTC, Konstantinos-Chaitas-PubNative commented on mlflow/Makefile
> +DOCKER_REPO_VERSION=$(DOCKER_REPO):$(VERSION)
In the version we can use the mlflow version plus the git commit

2023-06-06 13:41 UTC, Konstantinos-Chaitas-PubNative commented on mlflow/Dockerfile
> +FROM --platform=linux/amd64 python:3.8.10 AS build
I think it will be better to use the official MLflow Docker image directly

https://mlflow.org/docs/latest/docker.html

2023-06-16 09:12 UTC, pmittal-verve commented
@Konstantinos-Chaitas-PubNative updated please approve.

2023-06-16 09:20 UTC, Konstantinos-Chaitas-PubNative approved these changes

2023-06-16 09:37 UTC, merged