Creating a Druid image for testing Halo
pubnative/docker-images pull request #201
Opened 2023-11-20 09:16 UTC by alifouzizadeh

I confirm that I have added:

- [x] A comment to every Dockerfile with information about target repository and tag (version).
- [x] Filled in readme on dockerhub and in this repo about how to build the image if some extra steps should be done.

2023-11-20 16:19 UTC, mpasa requested changes

2023-11-20 16:19 UTC, mpasa commented on druid/single-container-druid/README.md
> +- **Custom Configuration**: This image includes additional packages and configurations not present in the official Druid
`perl` not present for running `start-micro-quickstart`

2023-11-20 16:19 UTC, mpasa commented on druid/single-container-druid/README.md
> +docker run  -p 8081:8081 -p 8082:8082 -p 8083:8083 -p 8888:8888 --name my-druid-container pubnative/single-container-druid:v28.0.0
Need to close the code block

2023-11-20 16:19 UTC, mpasa commented on druid/single-container-druid/README.md
> +
```suggestion
```

2023-11-20 16:43 UTC, Konstantinos-Chaitas-PubNative requested changes
Can we use the PROD image and pass arguments to it?

2023-11-20 16:43 UTC, Konstantinos-Chaitas-PubNative commented on druid/single-container-druid/Dockerfile
> +ENV DRUID_VERSION=28.0.0
This value here is hardcoded

2023-11-20 16:43 UTC, Konstantinos-Chaitas-PubNative commented on druid/single-container-druid/Dockerfile
> +FROM openjdk:8-jre
This value is also hardcoded

2023-11-20 16:43 UTC, Konstantinos-Chaitas-PubNative commented on druid/single-container-druid/Dockerfile
> +    && tar -xzf /tmp/druid.tar.gz -C /opt/druid --strip-components=1 \
We typically use the SHA for security reasons

2023-11-20 16:43 UTC, Konstantinos-Chaitas-PubNative commented on druid/single-container-druid/Makefile
> +DRUID_VERSION?=28.0.0
Lets update the Makefile following the conventions of AIrflow, Druid, etc..

https://github.com/pubnative/docker-images/pull/200/files#diff-a4396351d4bcc40059cfe8ef85d73ad81c1dd869dfb9a5a3a8570b62073d5499

2023-11-21 09:45 UTC, mpasa approved these changes

2023-11-21 13:24 UTC, alifouzizadeh commented
> Can we use the PROD image and pass arguments to it?

Totally with you on using upstream images. Tried docker-compose first, worked great locally but not on CircleCI. Then moved to the official Druid image, but it wasn’t right for us, it’s more  like for docker-compose or multi-node setups. Modifying the production one wasn’t an option, so I made a custom image instead. Even if we can handle the config and the env, running a single server requires `perl` package and it's not installed in the Official one. I've described this in the Readme file.

2023-11-21 14:47 UTC, Konstantinos-Chaitas-PubNative commented
> > Can we use the PROD image and pass arguments to it?
> 
> I already discussed this with @mpasa. Totally with you on using upstream images ( the prod image, in this case). Tried docker-compose first, worked great locally but not on CircleCI. Then moved to the official Druid image, but it wasn’t right for us, it’s more like for docker-compose or multi-node setups. Modifying the production one wasn’t an option, so I made a custom image instead. Even if we can handle the config and the env, running a single server requires `perl` package and it's not installed in the Official one. I've described this in the Readme file.

- What is the problem using docker-compose with CircleCI? I see here they have a guide explaining how it works
https://circleci.com/docs/docker-compose/

- Why do you think that it definitely needs `perl`, I can see this guy for instance doing that without it. My concern is that we will have to update multiple images on version upgrades, which adds maintenance overhead
https://github.com/rilldata/rill/blob/eb98cb2f071668134e8e363d0a0d7ebfc81f7558/scripts/druid-micro.dockerfile#L11

2023-11-22 08:40 UTC, Konstantinos-Chaitas-PubNative approved these changes

2023-11-22 08:46 UTC, mpasa approved these changes

2023-11-22 09:14 UTC, merged